In [1]:
# Két napi hőmérséklet-adatsor összefűzése
import numpy as np

nap1 = np.array([12.3, 13.1, 15.6, 18.0])
nap2 = np.array([11.9, 14.5, 17.2, 19.3])

# Feladat: fűzd össze a két nap adatait egy 1D tömbbe
osszes = np.concatenate((nap1, nap2))

print("Összesített hőmérséklet-adat:", osszes)

Összesített hőmérséklet-adat: [12.3 13.1 15.6 18.  11.9 14.5 17.2 19.3]


In [4]:
# Két szenzor adatait egymás mellé helyezni (hstack)

szenzor1 = np.array([5.1, 5.5, 5.8])
szenzor2 = np.array([4.9, 5.2, 5.6])

# legyen egy 2 oszlopos mátrix, ahol az 1. oszlop: szenzor1, 2.oszlop: szenzor2
egyutt = np.hstack((szenzor1.reshape(-1, 1), szenzor2.reshape(-1, 1)))

print("Két szenzor mérései együtt:\n", egyutt)

Két szenzor mérései együtt:
 [[5.1 4.9]
 [5.5 5.2]
 [5.8 5.6]]


In [5]:
# Napok egymás alá fűzése (vstack)

nap1 = np.array([12.3, 13.1, 15.6, 18.0])
nap2 = np.array([11.9, 14.5, 17.2, 19.3])
nap3 = np.array([10.5, 13.0, 15.5, 17.0])

# legyen 3 soros (nap), 4 oszlopos (mérés) táblázat
adatok = np.vstack((nap1, nap2, nap3))

print("3 nap hőmérsékleti adatai:\n", adatok)

3 nap hőmérsékleti adatai:
 [[12.3 13.1 15.6 18. ]
 [11.9 14.5 17.2 19.3]
 [10.5 13.  15.5 17. ]]


In [6]:
# RGB kép csatornák egyesítése (dstack)

piros = np.full((2, 2), 255)
zold  = np.zeros((2, 2))
kek   = np.full((2, 2), 128)

# egy 2×2×3 tömb, ahol az utolsó tengely a színeké
rgb = np.dstack((piros, zold, kek))
print("RGB tömb alakja:", rgb.shape)
print(rgb)

RGB tömb alakja: (2, 2, 3)
[[[255.   0. 128.]
  [255.   0. 128.]]

 [[255.   0. 128.]
  [255.   0. 128.]]]


In [7]:
# Több napi mérést 3D tömbbé alakítani (stack)

nap1 = np.array([10, 12, 15, 18])
nap2 = np.array([11, 13, 16, 19])
nap3 = np.array([12, 14, 17, 20])

# hozz létre egy új dimenziót, amely a napokat tárolja
heti_adatok = np.stack((nap1, nap2, nap3), axis=0)

print("Alak:", heti_adatok.shape)  # (3, 4)
print(heti_adatok)

Alak: (3, 4)
[[10 12 15 18]
 [11 13 16 19]
 [12 14 17 20]]


In [9]:
# Két kép vízszintes összefűzése (hstack képekkel)

bal = np.array([[1, 2],
                [3, 4]])
jobb = np.array([[5, 6],
                 [7, 8]])

# fűzd egymás mellé (2×4-es mátrix)
ossz = np.hstack((bal, jobb))
print(ossz)

[[1 2 5 6]
 [3 4 7 8]]
